package gg.jos.deathandtaxes;

import gg.jos.deathandtaxes.config.DeathTaxSettings;
import gg.jos.deathandtaxes.command.DeathAndTaxesCommand;
import gg.jos.deathandtaxes.listener.PlayerDeathTaxListener;
import gg.jos.deathandtaxes.service.CurrencyFormatter;
import net.kyori.adventure.text.minimessage.MiniMessage;
import net.milkbowl.vault.economy.Economy;
import org.bukkit.plugin.RegisteredServiceProvider;
import org.bukkit.plugin.java.JavaPlugin;

/**
 * Docs Generated by Documatic [Code]
 */

/**
 * Primary plugin entry point responsible for wiring configuration, Vault, and listeners.
 */
public final class DeathAndTaxesPlugin extends JavaPlugin {

    private Economy economy;
    private DeathTaxSettings settings;
    private CurrencyFormatter currencyFormatter;
    private MiniMessage miniMessage;

    /**
     * Bootstraps the plugin by loading configuration, connecting to Vault, and registering listeners.
     */
    @Override
    public void onEnable() {
        saveDefaultConfig();
        miniMessage = MiniMessage.miniMessage();
        reloadSettings();

        registerCommands();

        if (!setupEconomy()) {
            getLogger().severe("Vault economy provider not found. Disabling plugin.");
            getServer().getPluginManager().disablePlugin(this);
            return;
        }

        getServer().getPluginManager().registerEvents(new PlayerDeathTaxListener(this), this);
    }

    private void registerCommands() {
        if (getCommand("deathandtaxes") != null) {
            DeathAndTaxesCommand command = new DeathAndTaxesCommand(this);
            getCommand("deathandtaxes").setExecutor(command);
            getCommand("deathandtaxes").setTabCompleter(command);
        } else {
            getLogger().warning("Command registration failed for 'deathandtaxes'.");
        }
    }

    /**
     * Reloads settings from disk so administrators can apply configuration changes at runtime.
     */
    public void reloadSettings() {
        reloadConfig();
        settings = DeathTaxSettings.fromConfig(this, getConfig());
        currencyFormatter = new CurrencyFormatter(settings.getDecimalPlaces());
    }

    private boolean setupEconomy() {
        if (getServer().getPluginManager().getPlugin("Vault") == null) {
            return false;
        }

        RegisteredServiceProvider<Economy> registration = getServer().getServicesManager().getRegistration(Economy.class);
        if (registration == null) {
            return false;
        }

        economy = registration.getProvider();
        return true;
    }

    /**
     * Exposes the active Vault economy provider, or {@code null} if one could not be located.
     */
    public Economy getEconomy() {
        return economy;
    }

    /**
     * @return immutable snapshot of the current tax configuration.
     */
    public DeathTaxSettings getSettings() {
        return settings;
    }

    /**
     * @return formatter used to present currency amounts to players.
     */
    public CurrencyFormatter getCurrencyFormatter() {
        return currencyFormatter;
    }

    /**
     * @return shared MiniMessage instance for rendering Adventure components.
     */
    public MiniMessage getMiniMessage() {
        return miniMessage;
    }
}
